export { default as Details_product } from "./Details_product/Details_product";
export { default as Header } from "./Header/Header";
export { default as WhyChoos } from './WhyChoos/WhyChoos'
export { default as Navbar } from './Navbar/Navbar'
export { default as Footer } from './Footer/Footer'
export { default as ContactUs } from './ContactUs/ContactUs'
export { default as Verfiy_product } from './Verfiy_product/Verfiy_product'
export { default as Authenticity } from './Authenticity/Authenticity'
export { default as Counterfeits } from './Counterfeits/Counterfeits'       
export { default as Blog } from './Blog/Blog'       
export { default as AboutUs } from './AboutUs/AboutUs'       
export { default as Catego} from './Catego/Catego'       
export { default as Comments} from './Comments/Comments'       
export { default as Articel} from './Articel/Articel'       
export { default as OUR_INJECTABLES} from './OUR_INJECTABLES/OUR_INJECTABLES'       
export { default as OUR_TABLETS} from './OUR_TABLETS/OUR_TABLETS'       
export { default as TOP_SEARCH} from './TOP_SEARCH/TOP_SEARCH'       
export { default as AboutLong} from './AboutLong/AboutLong'       
